/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package principal;

/**
 *
 * @author Dick
 */
public class Recepcion extends javax.swing.JFrame {

    /**
     * Creates new form Recepcion
     */
    public Recepcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCBx_Servicios = new javax.swing.JComboBox();
        jText_Ci = new javax.swing.JTextField();
        jText_Telefono = new javax.swing.JTextField();
        jText_Costo = new javax.swing.JTextField();
        jRBttn_Tv = new javax.swing.JRadioButton();
        jRBttn_Wifi = new javax.swing.JRadioButton();
        jRBttn_Telf = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jText_Cli = new javax.swing.JTextField();
        jText_Estadia = new javax.swing.JTextField();
        jBttn_Cancelar = new javax.swing.JButton();
        jBttn_Guardar = new javax.swing.JButton();
        jBttn_Buscar = new javax.swing.JButton();
        foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RECEPCIÓN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Servicios :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cliente :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CI :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Costo :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Habitacion:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jCBx_Servicios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Doble", "Tripe", "Matrimonial", "Familiar" }));
        getContentPane().add(jCBx_Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, -1));
        getContentPane().add(jText_Ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, -1));
        getContentPane().add(jText_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, -1));
        getContentPane().add(jText_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 170, -1));

        jRBttn_Tv.setForeground(new java.awt.Color(255, 255, 255));
        jRBttn_Tv.setText("Tv/Cable");
        getContentPane().add(jRBttn_Tv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jRBttn_Wifi.setForeground(new java.awt.Color(255, 255, 255));
        jRBttn_Wifi.setText("Wiffi");
        getContentPane().add(jRBttn_Wifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jRBttn_Telf.setForeground(new java.awt.Color(255, 255, 255));
        jRBttn_Telf.setText("Telefono");
        getContentPane().add(jRBttn_Telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estadia :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jText_Cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_CliActionPerformed(evt);
            }
        });
        getContentPane().add(jText_Cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 170, -1));
        getContentPane().add(jText_Estadia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 170, -1));

        jBttn_Cancelar.setText("Cancelar");
        getContentPane().add(jBttn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        jBttn_Guardar.setText("Guardar");
        getContentPane().add(jBttn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jBttn_Buscar.setText("Buscar");
        getContentPane().add(jBttn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 419));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_CliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_CliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_CliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recepcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foto;
    private javax.swing.JButton jBttn_Buscar;
    private javax.swing.JButton jBttn_Cancelar;
    private javax.swing.JButton jBttn_Guardar;
    private javax.swing.JComboBox jCBx_Servicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRBttn_Telf;
    private javax.swing.JRadioButton jRBttn_Tv;
    private javax.swing.JRadioButton jRBttn_Wifi;
    private javax.swing.JTextField jText_Ci;
    private javax.swing.JTextField jText_Cli;
    private javax.swing.JTextField jText_Costo;
    private javax.swing.JTextField jText_Estadia;
    private javax.swing.JTextField jText_Telefono;
    // End of variables declaration//GEN-END:variables
}
